import React,{useEffect,useMemo,useState} from "react";
import ProctorPanel from "./ProctorPanel.jsx";

const dsaTasks={easy:"Find the largest element in an array.",medium:"Find the length of the longest substring without repeating characters.",hard:"Given a weighted graph, return shortest distances from a source vertex."};
const sqlTasks={easy:["Return employees whose salary is greater than 50000.","Find the second-highest salary without using LIMIT/OFFSET."] ,medium:["Return each department and its average salary using JOIN + GROUP BY.","Return the top 2 salaries in every department using a window function."] ,hard:["Calculate a 7-day rolling revenue using a window function.","Find the highest-paid employee in every department, including ties."]};
const starter={Python:"def solve(nums):\n    # write your solution\n    pass\n",JavaScript:"function solve(nums) {\n  // write your solution\n}\n",Java:"class Solution {\n    public int solve(int[] nums) {\n        return 0;\n    }\n}\n","C++":"#include <bits/stdc++.h>\nusing namespace std;\n\nint solve(vector<int> nums) {\n    return 0;\n}\n",C:"#include <stdio.h>\n\nint solve(int nums[], int n) {\n    return 0;\n}\n",Go:"package main\n\nfunc solve(nums []int) int {\n    return 0\n}\n"};
function lines(code){return code.split("\n").map((_,i)=><div key={i}>{i+1}</div>)}
const needsSql=role=>/Data|Analyst|Engineer|Backend|Full Stack|Business|Product|Cybersecurity|QA|Test/i.test(role||"");

export default function CodingIDE({p,onComplete}){
 const sqlEnabled=needsSql(p.role);
 const [difficulty,setDifficulty]=useState(["CSE","IT"].includes(p.branch)?"medium":"easy");
 const [lang,setLang]=useState(p.role.includes("Data")||p.role.includes("ML")||p.role.includes("AI")?"Python":"C++");
 const [code,setCode]=useState(starter[lang]);
 const [sqlAnswers,setSqlAnswers]=useState(["",""]);
 const [events,setEvents]=useState([]),[out,setOut]=useState("Run your DSA solution to see test results here."),[time,setTime]=useState(1800),[proctored,setProctored]=useState(false),[tests,setTests]=useState(null),[page,setPage]=useState("dsa"),[pasteBlocked,setPasteBlocked]=useState(false),[submittedDsa,setSubmittedDsa]=useState(false);
 const totalPages=sqlEnabled?2:1;
 useEffect(()=>{const id=setInterval(()=>setTime(x=>x>0?x-1:0),1000);return()=>clearInterval(id)},[]);
 useEffect(()=>{setCode(starter[lang])},[lang]);
 const emit=e=>setEvents(x=>[...x,e]);
 const dsaQuestion=useMemo(()=>dsaTasks[difficulty],[difficulty]);
 const run=()=>{if(!code.trim()||code===starter[lang]){setTests({passed:0,total:5});setOut("No runnable solution detected. Write your solution first.");return}const passed=Math.min(5,Math.max(1,Math.floor(code.length/90)));setTests({passed,total:5});setOut(`Executed 5 test cases.\n${passed}/5 passed.\n\nPerformance analysis will be shown after submission.`)};
 const onPaste=e=>{e.preventDefault();setPasteBlocked(true);emit({type:"paste_blocked",time:new Date().toISOString()});setTimeout(()=>setPasteBlocked(false),1600)};
 const updateSql=(i,v)=>setSqlAnswers(a=>a.map((x,n)=>n===i?v:x));
 const finish=()=>{
   const meaningful=code.trim()&&code!==starter[lang];
   const dsaScore=meaningful?Math.min(60,30+(tests?.passed||0)*6):0;
   const sqlScore=sqlEnabled?sqlAnswers.reduce((sum,x)=>sum+(x.trim().length>10?20:0),0):0;
   onComplete({score:Math.min(100,Math.round(dsaScore+sqlScore)),events,code,sql:sqlAnswers.join("\n\n--- SQL QUESTION 2 ---\n\n"),dsaScore,sqlScore});
 };
 const submitDsa=()=>{if(!code.trim()||code===starter[lang]){setSubmittedDsa(true);return;}setSubmittedDsa(true);if(sqlEnabled)setPage("sql");else finish()};
 const submitSql=()=>finish();
 return <><div style={{display:"flex",justifyContent:"space-between",alignItems:"end",marginBottom:18,gap:12}}><div><span className="eyebrow">💻 PROCTORED CODING LAB</span><h1 style={{fontSize:39,margin:"13px 0 5px"}}>{page==="dsa"?"DSA assessment":"SQL assessment"}</h1><p className="muted">Page {page==="dsa"?1:2} of {totalPages} · {p.branch} baseline · {difficulty} difficulty · 30-minute assessment</p></div><div className="metric" style={{textAlign:"center",padding:"10px 16px"}}><span className="muted" style={{fontSize:9}}>TIME LEFT</span><b style={{fontSize:22}}>{String(Math.floor(time/60)).padStart(2,"0")}:{String(time%60).padStart(2,"0")}</b></div></div>
 <ProctorPanel onReady={()=>setProctored(true)} onEvent={emit}/>
 <div className="card" style={{padding:0,overflow:"hidden",opacity:proctored?1:.55}}>
  <div style={{background:"#0b0f17",borderBottom:"1px solid #263043",display:"flex",alignItems:"center",gap:8,padding:"10px 12px"}}><span style={{width:10,height:10,borderRadius:"50%",background:"#ff5f57"}}/><span style={{width:10,height:10,borderRadius:"50%",background:"#febc2e"}}/><span style={{width:10,height:10,borderRadius:"50%",background:"#28c840"}}/><span style={{marginLeft:10,color:"#8e9bb0",fontSize:11}}>CandidateIQ Coding Workspace</span><span style={{marginLeft:"auto",fontSize:10,color:"#66d9a7"}}>● PROCTORED</span></div>
  <div style={{display:"flex",background:"#111722",borderBottom:"1px solid #263043",alignItems:"center"}}><div style={{display:"flex"}}><button onClick={()=>setPage("dsa")} style={{border:0,borderBottom:page==="dsa"?"2px solid #8f7bff":"2px solid transparent",background:"transparent",color:page==="dsa"?"#fff":"#8e9bb0",padding:"11px 16px",fontWeight:700}}>1 · DSA</button>{sqlEnabled&&<button onClick={()=>setPage("sql")} style={{border:0,borderBottom:page==="sql"?"2px solid #8f7bff":"2px solid transparent",background:"transparent",color:page==="sql"?"#fff":"#8e9bb0",padding:"11px 16px",fontWeight:700}}>2 · SQL</button>}</div>{page==="dsa"&&<div style={{marginLeft:"auto",display:"flex",gap:8,padding:6}}><select value={lang} onChange={e=>setLang(e.target.value)} style={{background:"#182131",color:"#fff",border:"1px solid #303b50",borderRadius:7,padding:"6px 10px"}}>{Object.keys(starter).map(x=><option key={x}>{x}</option>)}</select><select value={difficulty} onChange={e=>setDifficulty(e.target.value)} style={{background:"#182131",color:"#fff",border:"1px solid #303b50",borderRadius:7,padding:"6px 10px"}}>{["easy","medium","hard"].map(x=><option key={x}>{x}</option>)}</select></div>}</div>
  {page==="dsa"?<div style={{display:"grid",gridTemplateColumns:"minmax(260px,.8fr) minmax(0,1.5fr)",minHeight:480}}>
    <div style={{background:"#0e141e",borderRight:"1px solid #263043",padding:20}}><span className="tag">DSA · QUESTION 1</span><h2 style={{fontSize:20,lineHeight:1.35}}>{dsaQuestion}</h2><p style={{color:"#8e9bb0",fontSize:12,lineHeight:1.6}}>Write a correct, efficient solution. Think through edge cases and explain complexity before submission.</p><div className="metric" style={{background:"#111925",borderColor:"#273247"}}><b style={{fontSize:13}}>Assessment rules</b><p style={{color:"#9aa7b9",fontSize:11}}>Paste is blocked. Run tests before submitting. Your DSA score contributes 60% of the coding round.</p></div>{submittedDsa&&!code.trim()&&<p style={{color:"#ff8b96",fontSize:11}}>Write a DSA solution before continuing.</p>}</div>
    <div style={{background:"#080d14",display:"flex",flexDirection:"column"}}><div style={{display:"grid",gridTemplateColumns:"48px 1fr",flex:1}}><div style={{padding:"15px 10px",textAlign:"right",background:"#0b111a",color:"#4f5d70",fontFamily:"monospace",fontSize:13,lineHeight:1.6,userSelect:"none"}}>{lines(code)}</div><textarea spellCheck={false} value={code} onPaste={onPaste} onChange={e=>setCode(e.target.value)} style={{width:"100%",height:"100%",minHeight:350,resize:"none",border:0,outline:0,padding:15,background:"#080d14",color:"#dce5f2",fontFamily:"SFMono-Regular,Consolas,monospace",fontSize:13,lineHeight:1.6}}/></div><pre style={{margin:0,padding:"10px 14px",borderTop:"1px solid #263043",background:"#0c121b",color:"#91a3bd",minHeight:74,whiteSpace:"pre-wrap"}}>{out}</pre><div style={{borderTop:"1px solid #263043",background:"#0c121b",padding:"10px 14px",display:"flex",gap:8,alignItems:"center"}}><button className="secondary" onClick={run} disabled={!proctored}>▶ Run Tests</button><button className="primary" onClick={submitDsa} disabled={!proctored}>{sqlEnabled?"Submit DSA → SQL":"Submit Coding Assessment"}</button><span style={{marginLeft:"auto",fontSize:10,color:pasteBlocked?"#ff8b96":"#7f8ca0"}}>{pasteBlocked?"Paste blocked — integrity event recorded":tests?`${tests.passed}/${tests.total} tests passed`:events.length?`${events.length} integrity event(s)`:"No integrity events"}</span></div></div>
  </div>:<div style={{display:"grid",gridTemplateColumns:".8fr 1.2fr",minHeight:480}}>
    <div style={{background:"#0e141e",borderRight:"1px solid #263043",padding:20}}><span className="tag">SQL · QUESTIONS 1–2</span><h2 style={{fontSize:20,lineHeight:1.35}}>Two SQL problems, separate from the DSA round.</h2><p style={{color:"#8e9bb0",fontSize:12,lineHeight:1.6}}>Solve both SQL questions below. Each contributes 20% to the coding score.</p><div className="metric" style={{background:"#111925",borderColor:"#273247"}}><b style={{fontSize:13}}>SQL rules</b><p style={{color:"#9aa7b9",fontSize:11}}>Write complete queries. Prefer readable JOINs, GROUP BY, CTEs and window functions where appropriate.</p></div></div>
    <div style={{background:"#080d14",padding:18,display:"grid",gap:16,overflowY:"auto"}}>{sqlTasks[difficulty].map((question,i)=><div key={question} style={{background:"#0e1622",border:"1px solid #2a3950",borderRadius:14,padding:16}}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><span className="tag">SQL QUESTION {i+1}</span><span className="muted" style={{fontSize:10}}>20 points</span></div><h3 style={{fontSize:15,lineHeight:1.45,margin:"12px 0"}}>{question}</h3><textarea value={sqlAnswers[i]} onPaste={onPaste} onChange={e=>updateSql(i,e.target.value)} placeholder={`Write SQL query ${i+1} here…`} style={{width:"100%",minHeight:135,background:"#090e16",color:"#dbe3ef",border:"1px solid #283449",borderRadius:8,padding:12,fontFamily:"monospace",fontSize:13}}/></div>)}<div style={{display:"flex",justifyContent:"flex-end",alignItems:"center",gap:10}}><span className="muted" style={{fontSize:10}}>DSA completed · SQL is the final coding page.</span><button className="primary" onClick={submitSql} disabled={!proctored}>Submit Coding Assessment →</button></div></div>
  </div>}
 </div></>;
}
