import React,{useEffect,useRef,useState} from "react";

export default function ProctorPanel({onReady,onEvent,onTerminate}){
 const videoRef=useRef(null),streamRef=useRef(null),terminatedRef=useRef(false),violationsRef=useRef({}),faceMissRef=useRef(0),startedRef=useRef(false);
 const [status,setStatus]=useState("idle"),[error,setError]=useState(""),[full,setFull]=useState(false),[hasFrame,setHasFrame]=useState(false),[violation,setViolation]=useState("");
 const emit=(type,detail="")=>onEvent?.({type,detail,time:new Date().toISOString()});
 const stopTracks=()=>{streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;if(videoRef.current){try{videoRef.current.pause()}catch{}videoRef.current.srcObject=null}};
 const terminate=(type,detail)=>{if(terminatedRef.current)return;terminatedRef.current=true;setStatus("terminated");setViolation(detail);emit(type,detail);stopTracks();onTerminate?.({type,detail});};
 const recordViolation=(type,detail,limit=2,terminateNow=false)=>{const n=(violationsRef.current[type]||0)+1;violationsRef.current[type]=n;setViolation(`${detail} (${n}/${limit})`);emit(type,`${detail} | occurrence ${n}`);if(terminateNow||n>=limit)terminate("proctoring_terminated",`${detail}. Integrity policy triggered; assessment stopped.`);};
 const attachStream=async stream=>{const video=videoRef.current;if(!video)return;video.srcObject=stream;video.muted=true;video.playsInline=true;const play=async()=>{try{await video.play();setHasFrame(video.readyState>=2)}catch{setHasFrame(false)}};video.onloadedmetadata=play;video.onloadeddata=play;setTimeout(play,150);setTimeout(()=>{if(video.readyState<2)emit("camera_frame_warning","Camera stream connected but no video frame is visible yet.")},1200);};
 const goFullscreen=async()=>{try{if(document.fullscreenElement)return true;await document.documentElement.requestFullscreen?.();return Boolean(document.fullscreenElement)}catch(e){emit("fullscreen_error",e?.message||"");return false}};
 const enable=async()=>{setError("");setStatus("requesting");let fullscreenStarted=false;try{if(!navigator.mediaDevices?.getUserMedia)throw new Error("Camera and microphone access is not supported in this browser.");fullscreenStarted=await goFullscreen();if(!fullscreenStarted)throw new Error("Fullscreen is required for a proctored assessment. Allow fullscreen and click Start secure proctoring again.");setFull(true);const stream=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30,min:15},facingMode:"user"},audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true,channelCount:1}});const videoTrack=stream.getVideoTracks()[0],audioTrack=stream.getAudioTracks()[0];if(!videoTrack||!audioTrack)throw new Error("Both camera and microphone tracks are required.");streamRef.current=stream;await attachStream(stream);videoTrack.onended=()=>terminate("camera_lost","Camera feed ended. Restore camera access to continue.");audioTrack.onended=()=>terminate("microphone_lost","Microphone feed ended. Restore microphone access to continue.");videoTrack.onmute=()=>recordViolation("camera_muted","Camera feed was muted",1,true);audioTrack.onmute=()=>recordViolation("microphone_muted","Microphone feed was muted",1,true);startedRef.current=true;setStatus("ready");onReady?.(stream);emit("proctoring_started","Camera + microphone active; fullscreen locked for the assessment.");}catch(e){stopTracks();if(fullscreenStarted&&!document.fullscreenElement)fullscreenStarted=false;setStatus("denied");setError(e?.message||"Camera/microphone permission was denied.");emit("permission_error",e?.message||"");}};
 useEffect(()=>{if(status!=="ready")return;
   const paste=e=>{e.preventDefault();recordViolation("paste_blocked","Paste blocked",1,true)};
   const copy=e=>{e.preventDefault();recordViolation("copy_blocked","Copy blocked",3)};
   const cut=e=>{e.preventDefault();recordViolation("cut_blocked","Cut blocked",3)};
   const menu=e=>{e.preventDefault();recordViolation("context_menu","Context menu blocked",3)};
   const key=e=>{const mod=e.ctrlKey||e.metaKey;const k=e.key.toLowerCase();if(mod&&["c","v","x","a"].includes(k)){e.preventDefault();recordViolation(k==="v"?"paste_blocked":k==="c"?"copy_blocked":"cut_blocked",`${e.key.toUpperCase()} shortcut blocked`,k==="v"?1:3,k==="v");}if(e.key==="F12"||(mod&&e.shiftKey&&["i","j","c"].includes(k))){e.preventDefault();recordViolation("devtools_shortcut","Developer-tools shortcut blocked",1,true);}};
   const vis=()=>{if(document.hidden)terminate("tab_hidden","Assessment tab/window changed or was hidden. The interview has been stopped.");};
   const blur=()=>recordViolation("window_blur","Assessment window lost focus",1,true);
   const fs=()=>{const active=Boolean(document.fullscreenElement);setFull(active);if(!active&&startedRef.current)terminate("fullscreen_exit","Fullscreen was exited. The assessment has been stopped.");};
   document.addEventListener("paste",paste,true);document.addEventListener("copy",copy,true);document.addEventListener("cut",cut,true);document.addEventListener("contextmenu",menu,true);document.addEventListener("keydown",key,true);document.addEventListener("visibilitychange",vis);window.addEventListener("blur",blur);document.addEventListener("fullscreenchange",fs);
   let faceTimer=null;const FaceDetectorClass=window.FaceDetector;if(FaceDetectorClass&&videoRef.current){const detector=new FaceDetectorClass({fastMode:true,maxDetectedFaces:3});faceTimer=setInterval(async()=>{if(terminatedRef.current||!videoRef.current||videoRef.current.readyState<2)return;try{const faces=await detector.detect(videoRef.current);if(faces.length===0){faceMissRef.current+=1;if(faceMissRef.current>=2)recordViolation("no_face","No face detected in the camera frame",1,true);}else if(faces.length>1){recordViolation("multiple_faces","Multiple faces detected in the camera frame",1,true);faceMissRef.current=0;}else faceMissRef.current=0;}catch{}},1500);}
   return()=>{document.removeEventListener("paste",paste,true);document.removeEventListener("copy",copy,true);document.removeEventListener("cut",cut,true);document.removeEventListener("contextmenu",menu,true);document.removeEventListener("keydown",key,true);document.removeEventListener("visibilitychange",vis);window.removeEventListener("blur",blur);document.removeEventListener("fullscreenchange",fs);if(faceTimer)clearInterval(faceTimer);if(!terminatedRef.current)stopTracks();startedRef.current=false;};
 },[status]);
 return <div className="card" style={{padding:16,marginBottom:16,borderColor:status==="ready"?"#3ddc9766":status==="terminated"?"#ff6b7a88":"var(--line)"}}><div style={{display:"flex",gap:14,alignItems:"center",flexWrap:"wrap"}}><div style={{width:260,height:150,borderRadius:14,overflow:"hidden",background:"#03050a",border:"1px solid var(--line)",position:"relative"}}><video ref={videoRef} autoPlay muted playsInline preload="auto" style={{display:"block",width:"100%",height:"100%",objectFit:"cover",transform:"scaleX(-1)",background:"#03050a"}}/>{status!=="ready"&&<div style={{position:"absolute",inset:0,display:"grid",placeItems:"center",color:"var(--muted)",fontSize:11,textAlign:"center",padding:12}}>Camera preview<br/>not enabled</div>}{status==="ready"&&!hasFrame&&<div style={{position:"absolute",inset:0,display:"grid",placeItems:"center",color:"var(--muted)",fontSize:11}}>Waiting for camera frame…</div>}{status==="ready"&&<span style={{position:"absolute",left:8,bottom:8,background:"#000a",padding:"4px 7px",borderRadius:7,fontSize:9}}>● LIVE</span>}</div><div style={{flex:1,minWidth:250}}><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><span className="tag">PROCTORED SESSION</span><span className="status" style={{fontSize:10,color:status==="ready"?"#3ddc97":"var(--muted)"}}><i style={{background:status==="ready"?"#3ddc97":"var(--muted)"}}/>{status==="ready"?"Camera + microphone + fullscreen active":status==="requesting"?"Securing camera, microphone and fullscreen…":status==="terminated"?"Assessment terminated":"Camera + microphone + fullscreen required"}</span></div><p className="muted" style={{fontSize:11,lineHeight:1.5,margin:"8px 0"}}>Strict monitoring: camera/microphone health, fullscreen, tab/window visibility, focus changes, copy/paste, context menu and supported face-count detection.</p>{error&&<div style={{color:"#ff8b96",fontSize:11,marginBottom:8}}>{error}</div>}{violation&&<div style={{color:"#ffb86b",fontSize:11,marginBottom:8}}>⚠ {violation}</div>}<div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{status!=="ready"&&status!=="terminated"&&<button className="primary" onClick={enable} disabled={status==="requesting"}>{status==="requesting"?"Securing session…":"Start secure proctoring"}</button>}{status==="ready"&&<span className="tag">🔒 FULLSCREEN LOCKED</span>}{status==="terminated"&&<span className="tag">🚨 SESSION STOPPED</span>}</div></div></div></div>;
}
