import React,{useEffect,useRef,useState} from "react";
import ProctorPanel from "./ProctorPanel.jsx";

const QUESTIONS={
 behavioral:["Tell me about yourself and walk me through your background.","What are your strongest skills, and can you give an example where you used them?","What is one weakness you are actively improving?","Tell me about a difficult project or problem you handled and what you learned."],
 motivation:["Why do you want this role?","Why are you interested in this company or type of work?","Where do you want your career to grow over the next few years?"],
 technical:["Explain your strongest project end-to-end and your personal contribution.","What was the hardest technical decision you made in that project?","How did you validate your solution and measure whether it worked?","What trade-off would you change if you rebuilt the project today?","How would you make that project production-ready and scalable?"],
 hr:["Tell me about a time you disagreed with a teammate. How did you handle it?","How do you respond when you receive critical feedback?","Why should we select you for this role?"]
};
const roleWords=r=>({"Data Scientist":["python","machine learning","statistics","model","data"],"Data Analyst":["sql","python","power bi","excel","analysis","dashboard"],"AI Engineer":["python","machine learning","llm","api","model"],"Software Engineer":["dsa","algorithm","system","api","testing"],"Full Stack Developer":["react","node","api","database","javascript"]}[r]||["python","project","testing","api","database"]);
function scoreAnswer(a,phase,role){const t=a.trim().toLowerCase();if(!t)return 0;const n=t.split(/\s+/).filter(Boolean).length;if(n<8)return 18;const keys=phase==="technical"?roleWords(role):phase==="motivation"?["role","company","learn","career","impact"]:phase==="hr"?["team","feedback","problem","learn","communication"]:["project","experience","learn","team","result"];const hits=keys.filter(k=>t.includes(k)).length;return Math.min(95,Math.round(30+Math.min(35,n*1.1)+hits*6));}
function chooseVoice(){const vs=window.speechSynthesis?.getVoices?.()||[];const en=vs.filter(v=>/^en(-|_)/i.test(v.lang));const preferred=[/samantha/i,/ava/i,/jenny/i,/aria/i,/allison/i,/google us english/i,/google.*us/i,/daniel/i,/alex/i];for(const re of preferred){const v=en.find(x=>re.test(x.name));if(v)return v;}return en.find(v=>v.localService&&v.default)||en.find(v=>v.localService)||en.find(v=>v.default)||en[0]||vs[0]||null;}

export default function VoiceInterviewStable({p,phase,onComplete}){
 const qs=QUESTIONS[phase]||QUESTIONS.behavioral;
 const [q,setQ]=useState(0),[answer,setAnswer]=useState(""),[answers,setAnswers]=useState([]),[listening,setListening]=useState(false),[speaking,setSpeaking]=useState(false),[ready,setReady]=useState(false),[voice,setVoice]=useState(null),[events,setEvents]=useState([]);
 const recognitionRef=useRef(null),runningRef=useRef(false),textRef=useRef(""),restartRef=useRef(null),generationRef=useRef(0),questionRef=useRef(0);
 const emit=e=>setEvents(x=>[...x,e]);
 useEffect(()=>{const load=()=>setVoice(chooseVoice());load();window.speechSynthesis?.addEventListener?.("voiceschanged",load);return()=>window.speechSynthesis?.removeEventListener?.("voiceschanged",load)},[]);
 const stop=()=>{runningRef.current=false;generationRef.current+=1;if(restartRef.current)clearTimeout(restartRef.current);restartRef.current=null;try{recognitionRef.current?.stop()}catch{}recognitionRef.current=null;setListening(false)};
 const start=({autoRestart=false}={})=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){emit({type:"voice_unavailable",detail:"Speech recognition is unavailable in this browser."});return;}if(runningRef.current&&!autoRestart)return;if(autoRestart)runningRef.current=false;const generation=++generationRef.current;const qAtStart=questionRef.current;const r=new SR();recognitionRef.current=r;r.lang="en-US";r.continuous=true;r.interimResults=true;r.maxAlternatives=1;r.onresult=e=>{if(qAtStart!==questionRef.current||generation!==generationRef.current)return;let finals="",interim="";for(let i=e.resultIndex;i<e.results.length;i++){const s=e.results[i][0].transcript;if(e.results[i].isFinal)finals+=s+" ";else interim+=s;}if(finals)textRef.current=(textRef.current+" "+finals).replace(/\s+/g," ").trim();setAnswer((textRef.current+(interim?" "+interim:"" )).replace(/\s+/g," ").trim());};r.onend=()=>{if(runningRef.current&&qAtStart===questionRef.current&&generation===generationRef.current){runningRef.current=false;restartRef.current=setTimeout(()=>{restartRef.current=null;if(qAtStart===questionRef.current)start({autoRestart:true})},100)}};r.onerror=e=>{if(e.error!=="aborted"&&e.error!=="no-speech"&&e.error!=="not-allowed")emit({type:"speech_error",detail:e.error});if(e.error==="not-allowed"){runningRef.current=false;setListening(false)}};runningRef.current=true;setListening(true);try{r.start()}catch{runningRef.current=false;restartRef.current=setTimeout(()=>start({autoRestart:true}),180)}};
 const speakQuestion=()=>{stop();window.speechSynthesis?.cancel();const u=new SpeechSynthesisUtterance(qs[q]);u.lang="en-US";u.rate=.9;u.pitch=1;u.volume=1;if(voice)u.voice=voice;u.onstart=()=>setSpeaking(true);u.onend=()=>setSpeaking(false);u.onerror=()=>setSpeaking(false);window.speechSynthesis?.speak(u)};
 useEffect(()=>{stop();questionRef.current=q;textRef.current="";setAnswer("");setSpeaking(false);if(window.speechSynthesis){const id=setTimeout(speakQuestion,250);return()=>clearTimeout(id)}},[q,voice]);
 const submit=()=>{const value=(textRef.current||answer).trim();if(!value){emit({type:"empty_answer",detail:`Question ${q+1} submitted without an answer`});return;}stop();window.speechSynthesis?.cancel();const all=[...answers,value];textRef.current="";setAnswer("");if(q<qs.length-1){setAnswers(all);setQ(q+1)}else{const scores=all.map(a=>scoreAnswer(a,phase,p.role));onComplete({score:Math.round(scores.reduce((a,b)=>a+b,0)/scores.length),answers:all,events})}};
 return <><div style={{marginBottom:20}}><span className="eyebrow">🎙 {phase.toUpperCase()} INTERVIEW</span><h1 style={{fontSize:40,margin:"14px 0 6px"}}>{phase==="behavioral"?"Start with your story.":phase==="motivation"?"Now let's talk about the role.":phase==="technical"?"Show your technical depth.":"Let's finish with HR."}</h1><p className="muted">Question {q+1} of {qs.length} · Speak naturally. The microphone keeps running until you submit.</p></div><ProctorPanel onReady={()=>setReady(true)} onEvent={emit}/><div className="card" style={{maxWidth:960,margin:"auto",opacity:ready?1:.55}}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><span className="tag">AI INTERVIEWER</span><span className="muted" style={{fontSize:10}}>{voice?`Voice: ${voice.name}`:"Natural browser voice"}</span></div><div className="divider"/><div style={{textAlign:"center"}}><div style={{width:92,height:92,borderRadius:"50%",margin:"0 auto",display:"grid",placeItems:"center",background:"linear-gradient(135deg,#8065ff,#4e38c8)",boxShadow:speaking?"0 0 0 14px var(--soft),0 0 40px #8065ff66":"0 0 0 10px var(--soft)",fontSize:30}}>✦</div><div className="muted" style={{fontSize:11,marginTop:15}}>{speaking?"AI is speaking…":listening?"Microphone active — keep speaking":"Ready"}</div><h2 style={{fontSize:25,lineHeight:1.4,maxWidth:760,margin:"20px auto"}}>{qs[q]}</h2><div style={{display:"flex",justifyContent:"center",gap:8,flexWrap:"wrap"}}><button className="secondary" onClick={speakQuestion} disabled={!ready||speaking}>🔊 Repeat question</button>{!listening?<button className="primary" onClick={()=>start()} disabled={!ready||speaking}>🎙 Start answer</button>:<button className="secondary" onClick={stop}>⏸ Pause microphone</button>}</div><textarea className="input" value={answer} onChange={e=>{textRef.current=e.target.value;setAnswer(e.target.value)}} placeholder="Your live transcript appears here…" style={{minHeight:150,maxWidth:760,margin:"20px auto 0",display:"block"}}/><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,maxWidth:760,margin:"10px auto 0"}}><span className="muted" style={{fontSize:10}}>Each question starts with a clean transcript. If the browser stops recognition, it silently reconnects without losing your words.</span><button className="primary" onClick={submit} disabled={!ready}>{q===qs.length-1?"Submit & continue →":"Submit answer →"}</button></div></div></div></>;
}
