import React,{useEffect,useRef,useState} from "react";
import ProctorPanel from "./ProctorPanel.jsx";
import {HR_BANK,PROJECT_BANK,selectQuestions,technicalQuestions} from "./questionBank.js";

const phaseTitle={behavioral:"Start with your story.",motivation:"Let's talk about the role.",technical:"Show your technical depth.",project:"Let's go deeper into your project.",hr:"Let's finish with HR."};
const phaseLabel={behavioral:"BEHAVIORAL INTERVIEW",motivation:"MOTIVATION INTERVIEW",technical:"TECHNICAL INTERVIEW",project:"PROJECT DEEP DIVE",hr:"HR INTERVIEW"};
const roleWords=r=>({"Data Scientist":["python","machine learning","statistics","model","data"],"Data Analyst":["sql","python","power bi","excel","analysis","dashboard"],"AI Engineer":["python","machine learning","llm","api","model"],"Software Engineer":["dsa","algorithm","system","api","testing"],"Full Stack Developer":["react","node","api","database","javascript"]}[r]||["python","project","testing","api","database"]);
function scoreAnswer(a,phase,role){const t=a.trim().toLowerCase();if(!t)return 0;const n=t.split(/\s+/).filter(Boolean).length;if(n<8)return 18;const keys=phase==="technical"?roleWords(role):phase==="motivation"?["role","company","learn","career","impact"]:phase==="hr"?["team","feedback","problem","learn","communication"]:["project","experience","learn","team","result"];const hits=keys.filter(k=>t.includes(k)).length;return Math.min(95,Math.round(30+Math.min(35,n*1.1)+hits*6));}
function chooseVoice(){const vs=window.speechSynthesis?.getVoices?.()||[];const en=vs.filter(v=>/^en(-|_)/i.test(v.lang));const preferred=[/samantha/i,/ava/i,/jenny/i,/aria/i,/allison/i,/google us english/i,/google.*us/i,/daniel/i,/alex/i];for(const re of preferred){const v=en.find(x=>re.test(x.name));if(v)return v;}return en.find(v=>v.localService&&v.default)||en.find(v=>v.localService)||en.find(v=>v.default)||en[0]||vs[0]||null;}
function followUp(answer,phase,role){const t=answer.toLowerCase();const map=[['python','You mentioned Python. Which Python design or library choice made the biggest difference in that example, and why?'],['sql','You mentioned SQL. What was the hardest query or data problem you solved, and how did you validate the result?'],['machine learning','You mentioned machine learning. Why did you choose that model and which metric mattered most?'],['react','You mentioned React. How did you structure state and component responsibilities?'],['fastapi','You mentioned FastAPI. Why did you choose it and how would you scale the API?'],['project','You mentioned a project. What was your individual contribution and what would you improve today?'],['intern','You mentioned your internship. What measurable problem did you solve there?'],['github','You mentioned GitHub. Which repository best demonstrates your engineering ability and why?']];const hit=map.find(([k])=>t.includes(k));if(hit)return hit[1];if(phase==='behavioral')return 'You gave an overview. Tell me about one specific situation, what you personally did, and what the outcome was.';if(phase==='motivation')return `You explained your interest in the role. What specific impact would you like to make as a ${role}?`;return 'That answer gives me the context. What is the most important technical trade-off behind it?';}
function poolFor(phase,p,asked){if(phase==='project')return selectQuestions({phase:'project',askedIds:asked,limit:5});if(phase==='technical')return selectQuestions({phase:'technical',branch:p.branch||'CSE',askedIds:asked,limit:5});if(phase==='hr')return selectQuestions({phase:'hr',askedIds:asked,limit:5});const base=HR_BANK.map((question,i)=>({id:`${phase==='behavioral'?'BEH':'MOT'}-${i+1}`,question}));const filtered=phase==='behavioral'?base.filter(x=>/tell me|failure|teammate|ownership|deadline|criticism|conflict|mistake|prioritize|stress|manager|communication|team/i.test(x.question)):base.filter(x=>/why|role|company|career|motivat|goal|relocat|growth|work style|manager/i.test(x.question));const used=new Set(asked);let fresh=filtered.filter(x=>!used.has(x.id));for(let i=fresh.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[fresh[i],fresh[j]]=[fresh[j],fresh[i]];}return fresh.slice(0,5);}

export default function VoiceInterviewStable({p,phase,onComplete}){
 const [q,setQ]=useState(0),[answer,setAnswer]=useState(""),[answers,setAnswers]=useState([]),[listening,setListening]=useState(false),[speaking,setSpeaking]=useState(false),[ready,setReady]=useState(false),[voice,setVoice]=useState(null),[events,setEvents]=useState([]),[askedIds,setAskedIds]=useState([]),[qs,setQs]=useState([]);
 const recognitionRef=useRef(null),runningRef=useRef(false),finalTextRef=useRef(""),restartRef=useRef(null),generationRef=useRef(0),questionRef=useRef(0);
 const emit=e=>setEvents(x=>[...x,{...e,time:new Date().toISOString()}]);
 useEffect(()=>{const load=()=>setVoice(chooseVoice());load();window.speechSynthesis?.addEventListener?.("voiceschanged",load);return()=>window.speechSynthesis?.removeEventListener?.("voiceschanged",load)},[]);
 useEffect(()=>{const initial=poolFor(phase,p,[]);setQs(initial);setQ(0);setAnswers([]);setAskedIds([]);},[phase,p.branch,p.role]);
 const stop=()=>{runningRef.current=false;generationRef.current+=1;if(restartRef.current)clearTimeout(restartRef.current);restartRef.current=null;try{recognitionRef.current?.stop()}catch{}recognitionRef.current=null;setListening(false)};
 const start=({autoRestart=false}={})=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){emit({type:"voice_unavailable",detail:"Speech recognition is unavailable in this browser."});return;}if(runningRef.current&&!autoRestart)return;const generation=++generationRef.current;const qAtStart=questionRef.current;const r=new SR();recognitionRef.current=r;r.lang="en-US";r.continuous=true;r.interimResults=true;r.maxAlternatives=1;r.onresult=e=>{if(qAtStart!==questionRef.current||generation!==generationRef.current)return;let interim="";for(let i=e.resultIndex;i<e.results.length;i++){const s=e.results[i][0].transcript;if(e.results[i].isFinal)finalTextRef.current=(finalTextRef.current+" "+s).replace(/\s+/g," ").trim();else interim+=(" "+s);}setAnswer((finalTextRef.current+interim).replace(/\s+/g," ").trim());};r.onend=()=>{if(runningRef.current&&qAtStart===questionRef.current&&generation===generationRef.current){restartRef.current=setTimeout(()=>{restartRef.current=null;start({autoRestart:true})},120)}};r.onerror=e=>{if(e.error!=="aborted"&&e.error!=="no-speech"&&e.error!=="not-allowed")emit({type:"speech_error",detail:e.error});if(e.error==="not-allowed"){runningRef.current=false;setListening(false)}};runningRef.current=true;setListening(true);try{r.start()}catch{restartRef.current=setTimeout(()=>start({autoRestart:true}),180)}};
 const speakQuestion=text=>{stop();window.speechSynthesis?.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="en-US";u.rate=.96;u.pitch=1;u.volume=1;if(voice)u.voice=voice;u.onstart=()=>setSpeaking(true);u.onend=()=>setSpeaking(false);u.onerror=()=>setSpeaking(false);window.speechSynthesis?.speak(u)};
 useEffect(()=>{stop();questionRef.current=q;finalTextRef.current="";setAnswer("");setSpeaking(false);const text=qs[q]?.question;if(text&&window.speechSynthesis){const id=setTimeout(()=>speakQuestion(text),250);return()=>clearTimeout(id)}},[q,qs,voice]);
 const submit=()=>{const value=(finalTextRef.current||answer).trim();if(!value){emit({type:"empty_answer",detail:`Question ${q+1} submitted without an answer`});return;}stop();window.speechSynthesis?.cancel();const current=qs[q];const all=[...answers,value];const nextAsked=[...askedIds,current?.id].filter(Boolean);setAskedIds(nextAsked);finalTextRef.current="";setAnswer("");if(q<qs.length-1){setAnswers(all);setQ(q+1);return;}const scores=all.map(a=>scoreAnswer(a,phase,p.role));onComplete({score:Math.round(scores.reduce((a,b)=>a+b,0)/scores.length),answers:all,events,askedIds:nextAsked,followUp:followUp(value,phase,p.role)});};
 if(!qs.length)return <div className="card" style={{padding:50,textAlign:"center"}}>Loading question bank…</div>;
 const current=qs[q];
 return <><div style={{marginBottom:20}}><span className="eyebrow">🎙 {phaseLabel[phase]||"AI INTERVIEW"}</span><h1 style={{fontSize:40,margin:"14px 0 6px"}}>{phaseTitle[phase]||"Continue the interview."}</h1><p className="muted">Question {q+1} of {qs.length} · Speak naturally. The microphone keeps running until you submit.</p></div><ProctorPanel onReady={()=>setReady(true)} onEvent={emit}/><div className="card" style={{maxWidth:960,margin:"auto",opacity:ready?1:.55}}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><span className="tag">AI INTERVIEWER</span><span className="muted" style={{fontSize:10}}>{voice?`Natural voice · ${voice.name}`:"Natural browser voice"}</span></div><div className="divider"/><div style={{textAlign:"center"}}><div style={{width:92,height:92,borderRadius:"50%",margin:"0 auto",display:"grid",placeItems:"center",background:"linear-gradient(135deg,#8065ff,#4e38c8)",boxShadow:speaking?"0 0 0 14px var(--soft),0 0 40px #8065ff66":"0 0 0 10px var(--soft)",fontSize:30}}>✦</div><div className="muted" style={{fontSize:11,marginTop:15}}>{speaking?"AI is speaking…":listening?"Microphone active — keep speaking":"Ready"}</div><h2 style={{fontSize:25,lineHeight:1.4,maxWidth:760,margin:"20px auto"}}>{current.question}</h2><div style={{display:"flex",justifyContent:"center",gap:8,flexWrap:"wrap"}}><button className="secondary" onClick={()=>speakQuestion(current.question)} disabled={!ready||speaking}>🔊 Repeat question</button>{!listening?<button className="primary" onClick={()=>start()} disabled={!ready||speaking}>🎙 Start answer</button>:<span className="tag" style={{padding:"10px 14px"}}>● Listening continuously</span>}</div><textarea className="input" value={answer} onChange={e=>{finalTextRef.current=e.target.value;setAnswer(e.target.value)}} placeholder="Your live transcript appears here…" style={{minHeight:150,maxWidth:760,margin:"20px auto 0",display:"block"}}/><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,maxWidth:760,margin:"10px auto 0"}}><span className="muted" style={{fontSize:10}}>Transcript resets cleanly for every question and auto-reconnects if the browser ends recognition.</span><button className="primary" onClick={submit} disabled={!ready}>{q===qs.length-1?"Submit & continue →":"Submit answer →"}</button></div></div></div></>;
}
