import React, { useEffect, useRef, useState } from "react";
import AutoProctorPanel from "./AutoProctorPanel.jsx";
import { HR_BANK, selectQuestions } from "./questionBank.js";

const ROLE_WORDS={"Data Scientist":["python","machine learning","statistics","model","data"],"Data Analyst":["sql","python","power bi","excel","analysis","dashboard"],"AI Engineer":["python","machine learning","llm","api","model"],"ML Engineer":["python","machine learning","model","statistics"],"Software Engineer":["dsa","algorithm","system","api","testing"],"Software Developer":["java","python","dsa","algorithm","testing"],"Backend Developer":["api","database","python","java","sql"],"Frontend Developer":["javascript","react","html","css","frontend"],"Full Stack Developer":["react","node","api","database","javascript"],"Business Analyst":["sql","excel","power bi","requirements","stakeholder"]};
const MOTIVATION=["Why do you want this role, and why is it a good match for your current skills?","What part of this role would you be most excited to work on in your first six months?","How does this role fit into the direction you want your career to take?","What do you expect to learn in this role, and what value can you contribute immediately?","What keeps you motivated when a problem is difficult or ambiguous?"];
const FIRST={id:"BEH-SELF",question:"Tell me about yourself. Walk me through your background, skills, and experiences that are most relevant to this role."};
const shuffle=a=>{const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]];}return x;};
const historyKey=(p,phase)=>`candidateiq-${p.role}-${p.branch}-${phase}-interview-history`;
function readHistory(p,phase){try{return JSON.parse(sessionStorage.getItem(historyKey(p,phase))||"[]")}catch{return[]}}
function saveHistory(p,phase,ids){try{sessionStorage.setItem(historyKey(p,phase),JSON.stringify([...new Set(ids)].slice(-500)))}catch{}}
function scoreAnswer(text,phase,role){const t=String(text||"").trim().toLowerCase();const n=t?t.split(/\s+/).length:0;if(!n)return 0;if(n<8)return 18;let words=["project","experience","learn","team","result","skill"];if(phase==="technical")words=ROLE_WORDS[role]||words;if(phase==="motivation")words=["role","company","learn","career","impact","contribute"];if(phase==="hr")words=["team","feedback","problem","learn","communication","ownership"];return Math.min(95,Math.round(28+Math.min(38,n*1.05)+words.filter(w=>t.includes(w)).length*6));}
function followUp(answer,role){const t=String(answer||"").toLowerCase();const words=ROLE_WORDS[role]||["project","technology","testing","api","database"];const hit=words.find(w=>t.includes(w));return {id:`FOLLOW-${Date.now()}`,question:hit?`You mentioned ${hit}. Give me one concrete example of how you used it, what you personally did, and what result you achieved.`:"Which experience best demonstrates that you are ready for this role, and why?"};}
function makeQuestions(p,phase,history){const asked=new Set(history);if(phase==="behavioral"){const extra=shuffle(HR_BANK.map((q,i)=>({id:`BEH-${i+1}`,question:q})).filter(x=>!asked.has(x.id)&&!/tell me about yourself|why this role|why this company/i.test(x.question))).slice(0,2);return[FIRST,...extra];}if(phase==="motivation")return shuffle(MOTIVATION.map((q,i)=>({id:`MOT-${i+1}`,question:q})).filter(x=>!asked.has(x.id))).slice(0,3);if(phase==="technical")return selectQuestions({phase:"technical",branch:p.branch||"CSE",askedIds:history,limit:4});if(phase==="project")return selectQuestions({phase:"project",branch:p.branch||"CSE",askedIds:history,limit:4});return selectQuestions({phase:"hr",branch:p.branch||"CSE",askedIds:history,limit:4});}
function chooseVoice(){if(!window.speechSynthesis)return null;const v=window.speechSynthesis.getVoices()||[];const e=v.filter(x=>/^en(-|_)/i.test(x.lang));return e.find(x=>/samantha|ava|jenny|aria|google.*us|daniel|alex/i.test(x.name))||e[0]||v[0]||null;}

export default function VoiceInterviewStable({p,phase,onComplete}){
 const [questions,setQuestions]=useState([]),[index,setIndex]=useState(0),[answer,setAnswer]=useState(""),[answers,setAnswers]=useState([]),[listening,setListening]=useState(false),[speaking,setSpeaking]=useState(false),[ready,setReady]=useState(false),[voice,setVoice]=useState(null),[events,setEvents]=useState([]),[terminated,setTerminated]=useState(false),[reason,setReason]=useState(""),[speechStatus,setSpeechStatus]=useState("");
 const recognitionRef=useRef(null),activeRef=useRef(false),transcriptRef=useRef(""),timerRef=useRef(null),generationRef=useRef(0),questionRef=useRef(0),askedRef=useRef([]),retryRef=useRef(0);
 const emit=e=>{if(e?.type==="proctoring_started"||e?.type==="proctoring_ready")setReady(true);setEvents(cur=>[...cur,{...e,time:e?.time||new Date().toISOString()}]);};
 const clearRecognitionTimer=()=>{if(timerRef.current){clearTimeout(timerRef.current);timerRef.current=null;}};
 const stopListening=()=>{activeRef.current=false;generationRef.current++;retryRef.current=0;clearRecognitionTimer();try{recognitionRef.current?.abort()}catch{}recognitionRef.current=null;setListening(false);};
 useEffect(()=>{const h=readHistory(p,phase);askedRef.current=h;setQuestions(makeQuestions(p,phase,h));setIndex(0);setAnswers([]);setAnswer("");setReady(false);setTerminated(false);setReason("");setSpeechStatus("");},[p.role,p.branch,phase]);
 useEffect(()=>{const load=()=>setVoice(chooseVoice());load();window.speechSynthesis?.addEventListener?.("voiceschanged",load);return()=>window.speechSynthesis?.removeEventListener?.("voiceschanged",load)},[]);
 const speakQuestion=()=>{if(!window.speechSynthesis||!questions[index])return;stopListening();window.speechSynthesis.cancel();setSpeechStatus("");const u=new SpeechSynthesisUtterance(questions[index].question);u.lang="en-US";u.rate=.92;if(voice)u.voice=voice;u.onstart=()=>setSpeaking(true);u.onend=()=>setSpeaking(false);u.onerror=e=>{setSpeaking(false);setSpeechStatus("AI voice playback failed. You can still answer using the microphone.");emit({type:"speech_synthesis_error",detail:e?.error||"speech synthesis error"});};window.speechSynthesis.speak(u);};
 const startSegment=(token,q,retry=0)=>{if(!activeRef.current||terminated||token!==generationRef.current||q!==questionRef.current)return;const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition){activeRef.current=false;setListening(false);setSpeechStatus("Speech recognition is not supported by this browser. Please use Chrome or Edge.");return;}const r=new Recognition();r.lang="en-US";r.continuous=true;r.interimResults=true;r.maxAlternatives=1;recognitionRef.current=r;
   r.onaudiostart=()=>setSpeechStatus("Microphone connected — speak now.");
   r.onsoundstart=()=>setSpeechStatus("Listening…");
   r.onspeechstart=()=>setSpeechStatus("Speech detected — transcribing…");
   r.onresult=e=>{if(token!==generationRef.current||q!==questionRef.current||!activeRef.current)return;let interim="",finalText="";for(let i=e.resultIndex;i<e.results.length;i++){const text=e.results[i][0]?.transcript||"";if(e.results[i].isFinal)finalText+=text+" ";else interim+=text+" ";}if(finalText)transcriptRef.current=(transcriptRef.current+" "+finalText).replace(/\s+/g," ").trim();setAnswer((transcriptRef.current+" "+interim).replace(/\s+/g," ").trim());retryRef.current=0;setSpeechStatus(finalText?"Transcribing…":"Listening…");};
   r.onerror=e=>{const code=e?.error||"unknown";if(code!=="aborted")emit({type:"speech_error",detail:code});if(token!==generationRef.current||q!==questionRef.current||!activeRef.current)return;if(code==="not-allowed"||code==="service-not-allowed"){activeRef.current=false;setListening(false);setSpeechStatus("Microphone/speech permission was blocked. Allow microphone access, then press Start answer again.");return;}if(code==="network")setSpeechStatus("Speech service connection interrupted — reconnecting…");else if(code==="no-speech")setSpeechStatus("No speech detected — you can pause and continue speaking.");else if(code!=="aborted")setSpeechStatus(`Speech recognition error: ${code}. Reconnecting…`);};
   r.onend=()=>{if(token!==generationRef.current||q!==questionRef.current||terminated||!activeRef.current)return;recognitionRef.current=null;retryRef.current=Math.min(retryRef.current+1,5);const delay=Math.min(250*retryRef.current,1500);setSpeechStatus("Listening continuously — reconnecting microphone…");clearRecognitionTimer();timerRef.current=setTimeout(()=>startSegment(token,q,retryRef.current),delay);};
   try{r.start();setListening(true);setSpeechStatus("Microphone connected — speak now.");}catch(e){recognitionRef.current=null;if(token!==generationRef.current||q!==questionRef.current||terminated||!activeRef.current)return;retryRef.current=Math.min(retryRef.current+1,5);const delay=Math.min(300*retryRef.current,1800);setSpeechStatus("Starting microphone recognition…");clearRecognitionTimer();timerRef.current=setTimeout(()=>startSegment(token,q,retryRef.current),delay);}
 };
 const startListening=()=>{if(terminated||speaking||!ready||activeRef.current)return;const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition){setSpeechStatus("Speech recognition is not supported by this browser. Please use Chrome or Edge.");return;}stopListening();activeRef.current=true;const token=++generationRef.current;const q=questionRef.current;retryRef.current=0;setSpeechStatus("Connecting to speech recognition…");setListening(true);startSegment(token,q,0);};
 useEffect(()=>{stopListening();questionRef.current=index;transcriptRef.current="";setAnswer("");setSpeechStatus("");setSpeaking(false);if(!questions[index]||terminated)return;timerRef.current=setTimeout(speakQuestion,300);return()=>clearRecognitionTimer();},[index,questions,terminated,voice]);
 useEffect(()=>()=>{stopListening();window.speechSynthesis?.cancel();},[]);
 const terminate=info=>{stopListening();window.speechSynthesis?.cancel();const detail=info?.detail||"Integrity policy violation detected.";setTerminated(true);setReason(detail);emit({type:"interview_terminated",detail});};
 const submit=()=>{if(terminated)return;const value=(transcriptRef.current||answer).trim();if(!value){setSpeechStatus("No answer captured yet. Speak first, then submit.");emit({type:"empty_answer",detail:`Question ${index+1} submitted without an answer`});return;}stopListening();window.speechSynthesis?.cancel();const current=questions[index];const nextAnswers=[...answers,{id:current.id,question:current.question,answer:value}];const nextAsked=[...askedRef.current,current.id];if(phase==="behavioral"&&index===0){const f=followUp(value,p.role);setQuestions(cur=>[cur[0],f,...cur.slice(1)]);nextAsked.push(f.id);}askedRef.current=nextAsked;saveHistory(p,phase,nextAsked);if(index<questions.length-1){setAnswers(nextAnswers);setIndex(i=>i+1);return;}const scores=nextAnswers.map(x=>scoreAnswer(x.answer,phase,p.role));const score=scores.length?Math.round(scores.reduce((a,b)=>a+b,0)/scores.length):0;onComplete({score,answers:nextAnswers,events,askedIds:nextAsked});};
 if(!questions.length)return <div className="card" style={{padding:42,textAlign:"center"}}><h2>Preparing interview questions...</h2><p className="muted">Selecting fresh role-aware questions.</p></div>;
 if(terminated)return <div className="card" style={{padding:42,textAlign:"center",borderColor:"#ff6b7a88"}}><div style={{fontSize:42}}>🚨</div><h1>Interview stopped</h1><p className="muted">{reason}</p><span className="tag">SESSION FLAGGED FOR REVIEW</span></div>;
 const q=questions[index];const title=phase==="behavioral"?"Start with your story.":phase==="motivation"?"Now let's talk about the role.":phase==="technical"?"Show your technical depth.":phase==="project"?"Let's talk about your projects.":"Let's finish with HR.";
 return <div><div style={{marginBottom:20}}><span className="eyebrow">VOICE INTERVIEW · {String(phase).toUpperCase()}</span><h1 style={{fontSize:40,margin:"14px 0 6px"}}>{title}</h1><p className="muted">Question {index+1} of {questions.length} · Speak naturally and submit when finished.</p></div><AutoProctorPanel onReady={()=>setReady(true)} onEvent={emit} onTerminate={terminate}/><div className="card" style={{maxWidth:960,margin:"auto",opacity:ready?1:.55}}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><span className="tag">AI INTERVIEWER</span><span className="muted" style={{fontSize:10}}>{voice?`Natural voice · ${voice.name}`:"Natural browser voice"}</span></div><div className="divider"/><div style={{textAlign:"center"}}><div style={{width:90,height:90,borderRadius:"50%",margin:"0 auto",display:"grid",placeItems:"center",background:"linear-gradient(135deg,#8065ff,#4e38c8)",fontSize:30}}>✦</div><div className="muted" style={{fontSize:11,marginTop:15}}>{speaking?"AI is speaking...":listening?"Microphone active — keep speaking":"Ready"}</div><h2 style={{fontSize:25,lineHeight:1.4,maxWidth:760,margin:"20px auto"}}>{q.question}</h2><div style={{display:"flex",justifyContent:"center",gap:8,flexWrap:"wrap"}}><button className="secondary" onClick={speakQuestion} disabled={!ready||speaking}>Repeat question</button><button className="primary" onClick={startListening} disabled={!ready||speaking||listening}>Start answer</button>{listening&&<span className="tag">Listening continuously</span>}</div><textarea className="input" value={answer} onChange={e=>{transcriptRef.current=e.target.value;setAnswer(e.target.value)}} placeholder="Your live transcript appears here..." style={{minHeight:150,maxWidth:760,margin:"20px auto 0",display:"block"}}/><div style={{maxWidth:760,margin:"8px auto 0",textAlign:"left",minHeight:18}}>{speechStatus&&<span className="muted" style={{fontSize:10}}>🎙 {speechStatus}</span>}</div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,maxWidth:760,margin:"4px auto 0"}}><span className="muted" style={{fontSize:10}}>Your transcript is preserved while recognition reconnects, including normal 5–6 second thinking pauses.</span><button className="primary" onClick={submit} disabled={!ready}>{index===questions.length-1?"Submit & continue":"Submit answer"}</button></div></div></div></div>;
}
